djangoShopProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='main'),
    path('package_detail/<int:package_id>/<slug:package_slug>/', views.PackageDetailView.as_view(),
         name='package_detail'),
    path('category/<str:category_name>/', views.ShowPackagesView.as_view(), name='category_filter'),
    path('packages/show', views.ShowPackagesView.as_view(), name='show_package'),
    path('reply/<int:package_id>/<int:comment_id>', views.PackageReplyCommentView.as_view(), name='reply_comment'),
    path('save/<int:package_id>/', views.PackageSaveView.as_view(), name='package_save'),
    path('unsave/<int:package_id>/', views.PackageUnSaveView.as_view(), name='package_un_save'),
    path('send_email/', views.SendEmailView.as_view(), name='send_email')

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart_view'),
    path('cart/add/<int:subscription_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>', views.OrederDetailView.as_view(), name='order_detail'),
    path('apply/<int:order_id>', views.CouponApplyView.as_view(), name='apply_coupon'),
    # path('request/', views.OrderSendRequest.as_view(), name='request'),
    # path('verify/', views.OrderVerify.as_view(), name='verify'),
]

orders/models.py
# django
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
# local
from main.models import Subscription
# Third-party


class Order(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='orders'
    )
    paid = models.BooleanField(
        default=False
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True
    )
    discount = models.IntegerField(
        blank=True,
        null=True,
        default=None
    )

    class Meta:
        ordering = (
            'paid',
            '-updated'
        )

    def __str__(self):
        return f'{self.user} - {str(self.id)}'

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='items'
    )
    subscription = models.ForeignKey(
        Subscription,
        on_delete=models.CASCADE,
        related_name='order_items'
    )
    price = models.IntegerField(
        null=True,
        blank=True,
    )

    def get_cost(self):
        return self.price

    def __str__(self):
        return str(self.id)


class Coupon(models.Model):
    code = models.CharField(
        max_length=30,
        unique=True
    )
    valid_form = models.DateTimeField(
        null=True,
        blank=True
    )
    valid_to = models.DateTimeField(
        null=True,
        blank=True
    )
    discount = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(90)],
        null=True,
        blank=True,
    )
    active = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.code

orders/forms.py
# django
from django import forms


# local

# Third-party

class CouponApplyForm(forms.Form):
    code = forms.CharField()

orders/views.py
# django
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.conf import settings
# local
from .models import Subscription, Order, OrderItem, Coupon
from .forms import CouponApplyForm
from .cart import Cart
# Third-party
import requests
import json
import datetime


# Create your views here.
class CartView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'orders/cart.html', {'cart': cart})


class CartAddView(LoginRequiredMixin, View):
    def post(self, request, subscription_id):
        cart = Cart(request)
        subscription = get_object_or_404(Subscription, id=subscription_id)

        cart.add(subscription)
        return redirect('orders:cart_view')


class OrederDetailView(LoginRequiredMixin, View):
    form_class = CouponApplyForm

    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        return render(request, 'orders/order.html', {'order': order, 'form': self.form_class})


class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order, subscription=item['subscription'], price=item['price'])
        cart.clear()
        return redirect('orders:order_detail', order.id)


class CouponApplyView(LoginRequiredMixin, View):
    form_class = CouponApplyForm

    def post(self, request, order_id):
        now = datetime.datetime.now()
        form = self.form_class(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            try:
                coupon = Coupon.objects.get(code__exact=code, valid_form__lte=now, valid_to__gte=now,
                                            active=True)
            except Coupon.DoesNotExist:
                messages.error(request, 'This coupon dose not exists')
                return redirect('orders:order_detail', order_id)
            order = Order.objects.get(id=order_id)
            order.discount = coupon.discount
            order.save()
            return redirect('orders:order_detail', order_id)

#
# # ? sandbox merchant
# if settings.SANDBOX:
#     sandbox = 'sandbox'
# else:
#     sandbox = 'www'
#
# ZP_API_REQUEST = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
# ZP_API_VERIFY = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
# ZP_API_STARTPAY = f"https://{sandbox}.zarinpal.com/pg/StartPay/"
#
# amount = 1000  # Rial / Required
# description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
# phone = 'YOUR_PHONE_NUMBER'  # Optional
# # Important: need to edit for realy server.
# CallbackURL = 'http://127.0.0.1:8080/verify/'
#

# class OrderSendRequest(View):
#     data = {
#         "MerchantID": settings.MERCHANT,
#         "Amount": amount,
#         "Description": description,
#         "Phone": phone,
#         "CallbackURL": CallbackURL,
#     }
#     data = json.dumps(data)
#     # set content length by data
#     headers = {'content-type': 'application/json', 'content-length': str(len(data))}
#     try:
#         response = requests.post(ZP_API_REQUEST, data=data, headers=headers, timeout=10)
#
#         if response.status_code == 200:
#             response = response.json()
#             if response['Status'] == 100:
#                 return {'status': True, 'url': ZP_API_STARTPAY + str(response['Authority']),
#                         'authority': response['Authority']}
#             else:
#                 return {'status': False, 'code': str(response['Status'])}
#         return response
#
#     except requests.exceptions.Timeout:
#         return {'status': False, 'code': 'timeout'}
#     except requests.exceptions.ConnectionError:
#         return {'status': False, 'code': 'connection error'}
#
#
# class OrderVerify(View):
#     def get(self, order_id):
#         order = Order.objects.filter(id=order_id)
#         data = {
#             "MerchantID": settings.MERCHANT,
#             "Amount": order.,
#             "Authority": authority,
#         }
#         data = json.dumps(data)
#         # set content length by data
#         headers = {'content-type': 'application/json', 'content-length': str(len(data))}
#         response = requests.post(ZP_API_VERIFY, data=data, headers=headers)
#
#         if response.status_code == 200:
#             response = response.json()
#             if response['Status'] == 100:
#                 return {'status': True, 'RefID': response['RefID']}
#             else:
#                 return {'status': False, 'code': str(response['Status'])}
#         return response

orders/templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cart{% endblock %}
{% block style %}
    <style>
        body {
            background-color: #fbf4da;
        }
    </style>
{% endblock %}

{% block content %}
    <section class="my-5">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                    <p><span class="h2">Shopping Cart </span></p>

                    <div class="card mb-4">
                        <div class="card-body p-4">
                            {% for item in cart %}
                                <div class="row align-items-center">
                                    <div class="col-md-2 d-flex justify-content-center">
                                        <div>
                                            <p class="small text-muted mb-4 pb-2">Name</p>
                                            <p class="lead fw-normal mb-0">Premium</p>
                                        </div>
                                    </div>
                                    <div class="col-md-2 d-flex justify-content-center">
                                        <div>
                                            <p class="small text-muted mb-4 pb-2">Time</p>
                                            <p class="lead fw-normal mb-0">{{ item.sub_time }}</p>
                                        </div>
                                    </div>
                                    <div class="col-md-2 d-flex justify-content-center">
                                        <div>
                                            <p class="small text-muted mb-4 pb-2">Quantity</p>
                                            <p class="lead fw-normal mb-0">1</p>
                                        </div>
                                    </div>
                                    <div class="col-md-2 d-flex justify-content-center">
                                        <div>
                                            <p class="small text-muted mb-4 pb-2">Price</p>
                                            <p class="lead fw-normal mb-0">{{ item.price }} R</p>
                                        </div>
                                    </div>
                                    <div class="col-md-2 d-flex justify-content-center">
                                        <div>
                                            <p class="small text-muted mb-4 pb-2">Total</p>
                                            <p class="lead fw-normal mb-0">{{ item.price }} R</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>

                    <div class="d-flex justify-content-end">
                        <form action="{% url 'orders:order_create' %}">
                            {% csrf_token %}
                            <button type="submit" data-mdb-button-init data-mdb-ripple-init
                                    class="btn btn-primary btn-lg">
                                Add to cart
                            </button>
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}


{% block content %}
    <h2>Checked</h2>
    <form action="{% url 'orders:apply_coupon' order.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Apply">
    </form>
    <p>Total : {{ order.get_total_price }}</p>
    <a href="#" class="btn btn-primary">Buy</a>

{% endblock %}