accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('verify/', views.UserVerifyView.as_view(), name='user_verify'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('password_reset/', views.UserResetPasswordView.as_view(), name='password_reset'),
    path('password_change/', views.UserChangePasswordView.as_view(), name='password_change'),
]

djangoShopProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='main'),
    path('package_detail/<int:package_id>/<slug:package_slug>/', views.PackageDetailView.as_view(),
         name='package_detail'),
    path('category/<str:category_name>/', views.ShowPackagesView.as_view(), name='category_filter'),
    path('packages/show', views.ShowPackagesView.as_view(), name='show_package'),
    path('reply/<int:package_id>/<int:comment_id>', views.PackageReplyCommentView.as_view(), name='reply_comment'),
    path('save/<int:package_id>/', views.PackageSaveView.as_view(), name='package_save'),
    path('unsave/<int:package_id>/', views.PackageUnSaveView.as_view(), name='package_un_save'),
    path('send_email/', views.SendEmailView.as_view(), name='send_email')

]

accounts/models.py
# django
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
# local
from .managers import UserManager
# Third-party
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        max_length=255,
        unique=True
    )
    phone_number = models.CharField(
        max_length=11,
        unique=True,
    )
    image = models.ImageField(

    )
    full_name = models.CharField(
        max_length=100
    )
    is_active = models.BooleanField(
        default=True
    )
    is_admin = models.BooleanField(
        default=False
    )
    bio = models.TextField(
        null=True,
        blank=True
    )
    objects = UserManager(

    )
    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = [
        'email',
        'full_name'
    ]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def is_sub(self):
        from main.models import SubscriptionBuy
        if self.id == SubscriptionBuy.user.id:
            return True
        return False


class OtpCode(models.Model):
    phone_number = models.CharField(
        max_length=11,
        unique=True
    )
    code = models.PositiveSmallIntegerField(

    )
    created = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return f'{self.phone_number} - {self.code} - {self.created}'

accounts/forms.py
from turtledemo.chaos import f
from django import forms
from .models import User, OtpCode
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from phonenumber_field.formfields import SplitPhoneNumberField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password',widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='confirm password',
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = (
            'email',
            'phone_number',
            'full_name'
        )

    def clean_password2(self):
        cd = self.cleaned_data

        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('Password dont match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserResetPasswordForm(forms.Form):
    phone_number = forms.CharField(
        max_length=11,
        label='',
        widget=forms.TextInput(attrs={'placeholder': 'Phone number'})
    )
    password1 = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    password2 = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm password'})
    )

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('Password dont match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserChangePasswordForm(forms.Form):
    password1 = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    password2 = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm password'})
    )


class UserChangeAdminForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text='you can change password using <a href="../password/">this form</a>'
    )

    class Meta:
        model = User
        fields = (
            'email',
            'phone_number',
            'full_name',
            'password',
            'last_login'
        )


class UserProfileChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'phone_number',
            'image',
            'full_name',
            'bio'
        )
        labels = {
            'bio': '',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update({'class': 'input_filed'})
        self.fields["phone_number"].widget.attrs.update({'class': 'input_filed'})
        self.fields["full_name"].widget.attrs.update({'class': 'input_filed'})
        self.fields["bio"].widget.attrs.update({'class': 'input_filed_bio'})


class UserRegisterForm(forms.Form):
    email = forms.EmailField(
        label='',
        widget=forms.TextInput(attrs={'placeholder': 'Email'})
    )
    full_name = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'placeholder': 'FullName'})
    )
    phone_number = forms.CharField(
        label='',
        max_length=11,
        widget=forms.TextInput(attrs={'placeholder': 'PhoneNumber'})
    )
    password = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('this email already exists')
        return email

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        user = User.objects.filter(phone_number=phone_number).exists()
        if user:
            raise ValidationError('this phone number already exists')
        OtpCode.objects.filter(phone_number=phone_number).delete()
        return phone_number


class VerifyCodeForm(forms.Form):
    code = forms.IntegerField(
        label='',
        widget=forms.TextInput(attrs={'placeholder': 'Verify Code'})
    )


class UserLoginForm(forms.Form):
    phone_number = forms.CharField(
        max_length=11,
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'PhoneNumber'})
    )
    password = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'}),
  )

accounts/views.py
# django
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
# local
from utils import send_otp_code
from .models import User, OtpCode
from .forms import UserRegisterForm, UserLoginForm, VerifyCodeForm, UserProfileChangeForm, UserResetPasswordForm, \
    UserChangePasswordForm
from main.models import Vote, SubscriptionBuy
# Third-party

import random


class UserRegisterView(View):
    form_class = UserRegisterForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            random_code = random.randint(1000, 9999)
            send_otp_code(form.cleaned_data['phone_number'], random_code)
            OtpCode.objects.create(phone_number=form.cleaned_data['phone_number'], code=random_code)
            request.session['user_register_info'] = {
                'phone_number': form.cleaned_data['phone_number'],
                'email': form.cleaned_data['email'],
                'full_name': form.cleaned_data['full_name'],
                'password': form.cleaned_data['password'],
            }
            messages.success(request, 'we send you a code ', 'success')
            return redirect('accounts:user_verify')

        return render(request, self.template_name, {'form': form})


class UserVerifyView(View):
    form_class = VerifyCodeForm

    def get(self, request):
        user_session = request.session['user_register_info']
        form = self.form_class
        code_instance = OtpCode.objects.get(phone_number=user_session['phone_number'])
        return render(request, 'accounts/verify.html', {'form': form, 'code': code_instance})

    def post(self, request):
        user_session = request.session['user_register_info']
        code_instance = OtpCode.objects.get(phone_number=user_session['phone_number'])
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                User.objects.create_user(
                    user_session['phone_number'],
                    user_session['email'],
                    user_session['full_name'],
                    user_session['password']
                )
                code_instance.delete()
                messages.success(request, 'You Regisered', 'success')
                return redirect('main:main')
            else:
                messages.error(request, 'this code is wrong', 'danger')
                return redirect('accounts:user_verify')
        return redirect('main:main')


class UserLoginView(View):
    form_class = UserLoginForm

    def get(self, request):
        form = self.form_class
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                phone_number=cd['phone_number'],
                password=cd['password']
            )
            if user:
                login(request, user)
                messages.success(request, 'You Loged in', 'success')
                return redirect('main:main')

            messages.error(request, 'this account not found !', 'danger')
            return redirect('accounts:user_login')

        return redirect('main:main')


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'you logouted', 'danger')
        return redirect('main:main')


class UserProfileView(LoginRequiredMixin, View):
    form_class = UserProfileChangeForm

    def get(self, request):
        form = self.form_class(instance=request.user)
        change_password_form = UserChangePasswordForm
        vote = Vote.objects.filter(user=request.user)
        sub_buy = SubscriptionBuy.objects.filter(user=request.user, purchased=True)
        return render(request, 'accounts/profile.html',
                      {'form': form, 'change_password_form': change_password_form, 'vote': vote,
                       'sub_buy': sub_buy})

    def post(self, request):
        form = self.form_class(request.POST or None, files=request.FILES, instance=request.user)
        print(form)
        if form.is_valid():
            form.save()
            messages.success(request, 'profile changed !')
            return redirect('accounts:user_profile')
        messages.error(request, 'profile do not changed !')
        return redirect('accounts:user_profile')


class UserResetPasswordView(View):
    form_class = UserResetPasswordForm
    template_name = 'accounts/password_reset.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.get(phone_number=cd['phone_number'])
            if user:
                if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
                    messages.error(request, 'password do not same')
                    return redirect(self.template_name)
                user.set_password(cd['password2'])
                user.save()
                messages.success(request, 'Your password Changed')
                return redirect('main:main')
            messages.error(request, 'The information is not correct')
            return redirect(self.template_name)


class UserChangePasswordView(View):
    form_class = UserChangePasswordForm

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.get(phone_number=request.user.phone_number)
            if cd['password1'] and cd['password2'] and cd['password1'] == cd['password2']:
                user.set_password(cd['password2'])
                user.save()
                messages.success(request, 'Your password Changed')
                return redirect("accounts:user_login")
            messages.error(request, 'password do not same')
            return redirect('accounts:user_profile')

        messages.error(request, 'The information is not correct')
        return redirect('accounts:user_profile')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
{% endblock %}
{% block content %}
    <form class="login_form text-black" action="" method="post">
    <h4 class="text-white">Login</h4>
        {% csrf_token %}
        {{ form }}
        <div class="login_button">
            <input class="btn btn-light fw-bold fs-5" type="submit" value="Login">
            <a href="{% url  'accounts:user_register' %}" class="btn btn-light fw-bold fs-5">Register</a>
        </div>
        <div><a class="change text-white" href="{% url 'accounts:password_reset' %}">Forgot Password</a></div>
    </form>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Chang Password{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/password_reset.css' %}">
{% endblock %}
{% block content %}
    <form class="change_password_form" action="" method="post">
    <h4 class="text-white">Change Password</h4>
        {% csrf_token %}
        {{ form }}
        <div class="change_password_button">
            <input class="btn btn-light fw-bold fs-5" type="submit" value="Change Password">
            <a href="{% url  'accounts:user_login' %}" class="btn btn-light fw-bold fs-5">Cancel</a>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/profile_item/general.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/profile_item/change_password.css' %}">

{% endblock %}
{% block content %}
    <div class="container cont light-style flex-grow-1 container-p-y">
        <h4 class="font-weight-bold text-dark py-3 mb-4 mt-4">
            Account settings
        </h4>
        <div class="card profile-card overflow-hidden">
            <div class="row no-gutters row-bordered row-border-light">
                <div class="col-md-3 pt-0">
                    <div class="list-group list-group-flush text-dark account-settings-links">
                        <a class="list-group-item list-group-item-action active" data-toggle="list"
                           href="#account-info">Info</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list"
                           href="#account-change-password">Change password</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list"
                           href="#edit-profile">Edit Profile</a>
                        <a class="list-group-item list-group-item-action"
                           href="{% url 'main:main' %}">Exit</a>

                    </div>
                </div>
                <div class="col-md-9">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="account-info">
                            <div class="card-body pb-2 text-dark">
                                <div style="display: flex;align-items: end; gap: 10px; justify-content: start">
                                    {% if  request.user.image %}
                                        <img class="rounded-circle" style="width: 50px;height: 50px"
                                             src="{{ request.user.image.url }}" alt="">
                                    {% else %}
                                    <img class="rounded-circle" style="width: 50px;height: 50px"
                                         src="{% static 'main/images/7440683.png' %}" alt="">
                                    {% endif %}
                                    <div>
                                        <h4 style="display: inline">{{ request.user.full_name | title }} </h4>
                                        <span>{{ request.user.email }}</span>
                                    </div>

                                </div>
                                <div class="bio">
                                    <span class="text-dark">Bio :</span>
                                    <div class="bio_text">
                                        {{ request.user.bio }}
                                    </div>
                                </div>

                            </div>
                            <hr class="border border-2 border-dark m-0 text-dark">
                            <div class="card-body pb-2 text-dark">
                                <h6 class="mb-4">Package Saved</h6>
                                {% for vt in vote %}
                                    <a href="{% url 'main:package_detail' vt.package.id vt.package.slug %}"
                                       class="btn btn-info">
                                        {{ vt.package.name }}
                                    </a>
                                {% endfor %}

                            </div>
                            <hr class="border border-2 border-dark m-0 text-dark">

                            <div class="card-body pb-2 text-dark">
                                <h6 class="mb-4">Subscribe</h6>
                                {% if sub_buy %}
                                    {% for sb in sub_buy %}
                                        <p class="alert alert-success">{{ sb.user.full_name }}
                                            | {{ sb.sub_type.sub_time_select }}</p>
                                        <p></p>
                                        {#                                    <p>{{ sb.is_active }}</p>#}
                                    {% endfor %}
                                {% else %}
                                    <p class="alert alert-info">dont have subscription</p>
                                {% endif %}

                            </div>
                        </div>

                        <div class="tab-pane fade" id="account-change-password">
                            <div class="card-body pb-2 mb-2">
                                <h4 class="text-dark">Change Password</h4>

                                <form action="{% url 'accounts:password_change' %}"
                                      method="post">
                                    <div class="change_password_form">
                                        {% csrf_token %}
                                        {{ change_password_form }}
                                    </div>

                                    <div class="change_password_button">
                                        <input type="submit" class="btn btn-light border-0 fw-bold fs-6"
                                               value="Change Password">
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="tab-pane fade pb-2" id="edit-profile">
                            <div class="card-body pb-2">
                                <h4 class="text-dark">Edit Profile</h4>
                                <form action="" method="post" enctype="multipart/form-data" class="general  media align-items-center">
                                    {% csrf_token %}
                                    <samp>Email : </samp>
                                    {{ form.email }}
                                    <samp>Phone Number : </samp>
                                    {{ form.phone_number }}
                                    <samp>Full Name : </samp>
                                    {{ form.full_name }}
                                    <samp>Bio : </samp>
                                    {{ form.bio }}
                                    <samp>Image : </samp>
                                    {{ form.image }}<br><br>
                                    <input class="btn btn-light fw-bold fs-6" type="submit" value="Edit Profile">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}
{% block script %}
    <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">
    </script>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Register{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/register.css' %}">
{% endblock %}

{% block content %}

    <form class="register_form" action="" method="post">
        <h4 class="text-white">Register</h4>
        {% csrf_token %}
        {{ form }}
        <div class="register_button">
            <input class="btn btn-light fw-bold fs-5" type="submit" value="Register">
            <a href="{% url 'accounts:user_login' %}" class="btn btn-light fw-bold fs-5">Login</a>
        </div>

    </form>
{% endblock %}

accounts/templates/accounts/verify.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Verify{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/verify.css' %}">
{% endblock %}
{% block content %}
    <form class="verify_form" action="" method="post">
        <h4 class="text-white">Verify</h4>
        <p class="text-white">{{ code }}</p>
        {% csrf_token %}
        {{ form }}
        <div class="verify_button">
            <input class="btn btn-light fw-bold fs-5" type="submit" value="Check">
        </div>
    </form>
{% endblock %}