djangoShopProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='main'),
    path('package_detail/<int:package_id>/<slug:package_slug>/', views.PackageDetailView.as_view(),
         name='package_detail'),
    path('category/<str:category_name>/', views.ShowPackagesView.as_view(), name='category_filter'),
    path('packages/show', views.ShowPackagesView.as_view(), name='show_package'),
    path('reply/<int:package_id>/<int:comment_id>', views.PackageReplyCommentView.as_view(), name='reply_comment'),
    path('save/<int:package_id>/', views.PackageSaveView.as_view(), name='package_save'),
    path('unsave/<int:package_id>/', views.PackageUnSaveView.as_view(), name='package_un_save'),
    path('send_email/', views.SendEmailView.as_view(), name='send_email')

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart_view'),
    path('cart/add/<int:subscription_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>', views.OrederDetailView.as_view(), name='order_detail'),
    path('apply/<int:order_id>', views.CouponApplyView.as_view(), name='apply_coupon'),
    # path('request/', views.OrderSendRequest.as_view(), name='request'),
    # path('verify/', views.OrderVerify.as_view(), name='verify'),
]

main/models.py
# django
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

# local
from accounts.models import User
from mptt.models import MPTTModel, TreeForeignKey
from ckeditor.fields import RichTextField
from datetime import date
import datetime


class Category(MPTTModel):
    name = models.CharField(
        max_length=200,
        verbose_name=_('name')
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children')
    slug = models.SlugField(
        max_length=200,
        unique=True
    )

    class MPTTMeta:
        order_insertion_by = [
            'name',
        ]

        verbose_name = 'my_category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_parent_url(self):
        return reverse(
            'main:category_filter',
            args=[
                self.name
            ]
        )


class Package(models.Model):
    category = models.ManyToManyField(
        Category,
        related_name='cat_package',
    )
    name = models.CharField(
        max_length=200,
        null=True,
        blank=True
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
    )
    image = models.ImageField(
        null=True,
        blank=True
    )
    description = RichTextField(
        blank=True,
        null=True,

    )
    available = models.BooleanField(
        default=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    is_premium = models.BooleanField(
        default=False,
    )
    update = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        ordering = (
            'name',
        )

    def __str__(self):
        return f'category : {self.category} name : {self.name}'

    def get_absolute_url(self):
        return reverse(
            'main:package_detail',
            args=[
                self.id,
                self.slug,
            ]
        )

    def user_can_like(self, user):
        user_like = user.u_vote.filter(package=self)
        if user_like.exists():
            return True
        return False


class Subscription(models.Model):
    sub_time = {
        'one-month': 30,
        'two-month': 60,
        'three-month': 90,
    }
    name = models.CharField(
        max_length=200,
        default='premium'
    )
    sub_time_select: str = models.CharField(
        max_length=11,
        choices=sub_time
    )
    image = models.ImageField(
        null=True,
        blank=True,
    )
    price = models.IntegerField(
        null=True,
        blank=True
    )
    available = models.BooleanField(
        default=True,
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    update = models.DateTimeField(
        auto_now=True
    )


class SubscriptionBuy(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user_sub'
    )
    sub_type = models.ForeignKey(
        Subscription,
        on_delete=models.CASCADE,
        related_name='sub_type'
    )
    purchased = models.BooleanField(
        default=True
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    update = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = [
            'purchased',
        ]

    def is_active(self):
        from django.utils import timezone
        time_sub = Subscription.sub_time_select
        return self.created <= timezone.now().date() <= timezone.now().date()

    def __str__(self):
        return f'user : {self.user} subType: {self.sub_type} created : {self.created}'


class Comment(MPTTModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='u_commits',
    )
    package = models.ForeignKey(
        Package,
        on_delete=models.CASCADE,
        related_name='p_commits'
    )
    content = models.TextField(
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )

    class MPTTMeta:
        order_insertion_by = [
            'created_at',
        ]

    def __str__(self):
        return f'Comment by {self.id}'


class Vote(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='u_vote'
    )
    package = models.ForeignKey(
        Package,
        on_delete=models.CASCADE,
        related_name='p_vote'
    )

    class Mete:
        ordering = (
            'package',
        )

    def __str__(self):
        return f'{self.user} Liked :  {self.package.slug}'

main/forms.py
# django
from django import forms
# local
from .models import Package, Comment
import phonenumber_field


# Third-party
class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'content',
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 4, 'id': 'textAreaExample'}),
        }
        labels = {
            'content': ''
        }


class ReplyCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'content',
            'parent'
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 4, 'id': 'textAreaExample'}),
        }
        labels = {
            'content': '',
            'parent': ''
        }


class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control me-3", "type": "search", "placeholder": "Search", "aria-label": "Search"}),
        label="",
    )


class SendEmailForm(forms.Form):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}))
    user_email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    subject = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Message'}))

main/views.py
# django
from xml.etree.ElementPath import get_parent_map
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.core.mail import send_mail
# local
from accounts.models import User
from .forms import Comment, CommentCreateForm, ReplyCommentForm, SearchForm, SendEmailForm
from .models import Package, Category, Subscription, SubscriptionBuy, Vote
# Third-party
from botocore import useragent


class HomePageView(View):
    def get(self, request):
        packages_free = Package.objects.filter(available=True, is_premium=False)
        packages_premium = Package.objects.filter(available=True, is_premium=True)
        sub = Subscription.objects.filter(available=True)
        form = SendEmailForm
        return render(request, 'main/index.html',
                      {'packages_free': packages_free, 'packages_premium': packages_premium, 'sub': sub, 'form': form})


class PackageDetailView(LoginRequiredMixin, View):
    form_class = CommentCreateForm
    form_class_reply = ReplyCommentForm

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.package_instance = None

    def setup(self, request, *args, **kwargs):
        self.package_instance = get_object_or_404(Package, pk=kwargs['package_id'], slug=kwargs['package_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = Comment.objects.all()
        can_like = False
        sub = False
        packages_premium = Package.objects.filter(available=True, is_premium=True, id=kwargs['package_id'])
        packages_free = Package.objects.filter(available=True, is_premium=False, id=kwargs['package_id'])
        packages = Package.objects.get(id=kwargs['package_id'])
        if request.user.is_authenticated and not SubscriptionBuy.objects.filter(user=request.user) and packages_premium:
            messages.error(request, 'you dont see this blog')
            return redirect('main:main')
        if request.user.is_authenticated and self.package_instance.user_can_like(request.user):
            can_like = True

        return render(request, 'main/detail.html',
                      {'posts': self.package_instance, 'comments': comments, 'forms': self.form_class()
                          , 'reply_form': self.form_class_reply(), 'can_like': can_like, 'packages_free': packages_free,
                       'packages_premium': packages_premium, 'sub': sub, 'packages': packages})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            new_comment = forms.save(commit=False)
            new_comment.user = request.user
            new_comment.package = self.package_instance
            new_comment.save()
            messages.success(request, 'Your Comment submitted successfully !')
        return redirect('main:package_detail', self.package_instance.id, self.package_instance.slug)


class PackageReplyCommentView(LoginRequiredMixin, View):
    form_class = ReplyCommentForm

    def post(self, request, package_id, comment_id):
        package = get_object_or_404(Package, id=package_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.package = package
            reply.save()
            messages.success(request, 'your reply submited successfully..')
        return redirect('main:package_detail', package.id, package.slug)


class ShowPackagesView(View):
    def get(self, request, category_name=None):
        packages_free = Package.objects.filter(available=True, is_premium=False)
        categories = Category.objects.all()
        form = SearchForm()
        packages_premium = Package.objects.filter(available=True, is_premium=True)
        if 'search' in request.GET:
            form = SearchForm(request.GET)
            if form.is_valid():
                cd = form.cleaned_data['search']
                packages_premium = Package.objects.filter(Q(name__icontains=cd) | Q(description__in=cd),
                                                          is_premium=True)
                packages_free = Package.objects.filter(Q(name__icontains=cd) | Q(description__in=cd), is_premium=False)

        if category_name:
            category = Category.objects.get(name=category_name)
            packages_free = packages_free.filter(category=category)
            packages_premium = packages_premium.filter(category=category)
        return render(request, 'package/show_packages.html', {
            'packages_free': packages_free,
            'packages_premium': packages_premium,
            'categories': categories,
            'form': form})


class PackageSaveView(View):
    def get(self, request, package_id):
        package = get_object_or_404(Package, id=package_id)
        like = Vote.objects.filter(package=package, user=request.user)
        if like.exists():
            messages.error(request, 'you have already liked this post...', 'danger')
        else:
            Vote.objects.create(package=package, user=request.user)
            messages.success(request, 'you saved this post ')
        return redirect('main:package_detail', package.id, package.slug)


class PackageUnSaveView(View):
    def get(self, request, package_id):
        package = get_object_or_404(Package, id=package_id)
        saved = Vote.objects.filter(package=package, user=request.user)
        if saved.exists():
            saved.delete()
            messages.success(request, 'you un saved this post')
            return redirect('main:package_detail', package.id, package.slug)


class SendEmailView(View):
    def post(self, request):
        form = SendEmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(cd['subject'], cd['message'], 'amir1386abbas4838@gmail.com', [cd['user_email']])
            messages.success(request, 'Send Email successfully !')
            return redirect('main:main')
        messages.error(request, 'Send Email Error !')
        return redirect('main:main')

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}
{% block style %}
    <link rel="stylesheet" href="{% static 'main/css/main/detail.css' %}">
{% endblock %}
{% block title %}{% endblock %}
{% block content %}
    <div class="container">
        {% for package_free in packages_free %}
            <div class="section-header">
                <div class="section-header_item">
                    <div class="section-header_item-img">
                        <img style="width: 60px;height: 60px;border: 2px solid black" src="{{ package_free.image.url }}"
                             class="rounded-circle"
                             style="width: 300px; height: 200px "
                             alt="...">
                    </div>
                    <div class="section-header_item-text">
                        <div>
                            <h5 class="card-title">{{ package_free.name }}</h5>
                            <p>Created : {{ package_free.user.full_name }}</p>
                        </div>

                    </div>
                    <div>
                        {% if can_like %}
                            <a href="{% url 'main:package_un_save' package_free.id %}"
                               class=" btn btn-primary m-2">Un Save to
                                Profile</a>
                        {% else %}

                            <a href="{% url 'main:package_save' package_free.id %}"
                               class=" btn btn-primary m-2">Save to
                                Profile</a>
                        {% endif %}


                    </div>
                </div>
            </div>
            <hr>

            <div>
                <p>{{ package_free.description | safe }}</p>
            </div>
        {% endfor %}
        {% for package_premium in packages_premium %}
            <div class="section-header">
                <div class="section-header_item">
                    <div class="section-header_item-img">
                        <img style="width: 60px;height: 60px;border: 2px solid black"
                             src="{{ package_premium.image.url }}"
                             class="rounded-circle"
                             style="width: 300px; height: 200px "
                             alt="...">
                    </div>
                    <div class="section-header_item_box">
                        <div class="section-header_item-text">
                            <h5 style="display: inline-block" class=""
                                style="display: flex; justify-content:space-between; align-items: center;">{{ package_premium.name }}
                                <img style="width: 25px;height: 25px"
                                     src="{% static 'main/images/icons8-star-48.ico' %}"
                                     alt="">
                            </h5>
                            <p>Created : {{ package_premium.user.full_name }}</p>
                        </div>
                    </div>
                    <div>
                        {% if can_like %}
                            <a href="{% url 'main:package_un_save' package_premium.id %}"
                               class=" btn btn-primary m-2">Un Save to
                                Profile</a>
                        {% else %}

                            <a href="{% url 'main:package_save' package_premium.id %}"
                               class=" btn btn-primary m-2">Save to
                                Profile</a>
                        {% endif %}
                    </div>
                </div>

            </div>
            <div>
                <p>{{ package_premium.description | safe }}</p>
            </div>
        {% endfor %}
    </div>
    <fieldset>
        <legend>Comments : {{ comments.count }}</legend>
        <div class="comment_box p-2">
            {% for comment in comments %}
                <div class="comment_box_item mx-3 my-3 card">
                    <h4 class="card-header comment_box_header_item text-dark"><img
                            class="border border-1 rounded-circle me-3"
                            src="{{ request.user.image.url }}" alt="avatar"
                            width="30"
                            height="30"/>{{ comment.user.full_name }}
                        | {{ comment.created | timesince }}</h4>
                    <p class="card-body text-black">{{ comment.content|safe }}</p>
                    {% recursetree comments %}
                        <div>{{ node.content }}</div>
                        <p>{{ children }}</p>
                    {% endrecursetree %}
                    {% if request.user.is_authenticated %}
                        {% for reply in comment.get_children %}
                            <div class="r_comment mx-3 my-3 card">pp
                                <div class="card-header r_comment_box_header_item text-dark">
                                    <h6 class="">{{ reply.user.full_name }}</h6>
                                </div>
                                <div class="p-2 bg-white">
                                    <p class="">{{ reply.body | safe }}</p>
                                </div>
                            </div>
                        {% endfor %}

                        <div class="p-3 m-2">
                            <form action="{% url 'main:reply_comment' packages.id comment.id %}" method="post">
                                {% csrf_token %}
                                {{ reply_form }}
                                <input type="submit" value="Reply Comment" data-mdb-button-init
                                       data-mdb-ripple-init
                                       class="mt-3 btn btn-send">
                            </form>
                        </div>
                    {% endif %}

                </div>

            {% empty %}
                <p>No Comments yet...</p>
            {% endfor %}
            <br>
            {% if request.user.is_authenticated %}
                <div class="mx-3 w-75 text-body">
                    <div class="row d-flex justify-content-start">
                        <div class="col-md-10 col-lg-8 col-xl-6">
                            <div class="card new_com">
                                <div class="card-body p-4">
                                    <div class=" w-100">
                                        <div class="d-flex mb-3 align-items-center">
                                            {% if request.user.image %}
                                                <img class="rounded-circle me-3"
                                                     src="{{ request.user.image.url }}" alt="avatar"
                                                     width="65"
                                                     height="65"/>
                                            {% else %}
                                                <img class="rounded-circle me-3" style="width: 50px;height: 50px"
                                                     src="{% static 'main/images/7440683.png' %}" alt="">
                                            {% endif %}
                                            <div>
                                                <h5>Add a comment</h5>
                                                <span>{{ request.user.full_name }}</span>
                                            </div>
                                        </div>

                                        <div class="w-100">
                                            <form action="" method="post">
                                                <div data-mdb-input-init class="form-outline">
                                                    {% csrf_token %}
                                                    {{ forms.as_p }}
                                                </div>
                                                <div class="d-flex justify-content-between mt-3">
                                                    <input type="submit" data-mdb-button-init data-mdb-ripple-init
                                                           class="btn btn-send">
                                                    </input>
                                                </div>
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </fieldset>
{% endblock %}