accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('verify/', views.UserVerifyView.as_view(), name='user_verify'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('password_reset/', views.UserResetPasswordView.as_view(), name='password_reset'),
    path('password_change/', views.UserChangePasswordView.as_view(), name='password_change'),
]

djangoShopProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='main'),
    path('package_detail/<int:package_id>/<slug:package_slug>/', views.PackageDetailView.as_view(),
         name='package_detail'),
    path('category/<str:category_name>/', views.ShowPackagesView.as_view(), name='category_filter'),
    path('packages/show', views.ShowPackagesView.as_view(), name='show_package'),
    path('reply/<int:package_id>/<int:comment_id>', views.PackageReplyCommentView.as_view(), name='reply_comment'),
    path('save/<int:package_id>/', views.PackageSaveView.as_view(), name='package_save'),
    path('unsave/<int:package_id>/', views.PackageUnSaveView.as_view(), name='package_un_save'),
    path('send_email/', views.SendEmailView.as_view(), name='send_email')

]

templates/inc/footer.html
<!-- Remove the container if you want to extend the Footer to full width. -->
  <footer class="my-5" style="background-color: #ff9b296e;">
    <div class="container p-4">
      <div class="row ">
        <div class="col-lg-6 col-md-12 mb-4">
          <h5 class="mb-3 text-dark">footer content</h5>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
            molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
            voluptatem veniam, est atque cumque eum delectus sint!
          </p>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-3 text-dark">links</h5>
          <ul class="list-unstyled  mb-0">
            <li class="mb-1">
              <a href="#!" class="text-decoration-none" style="color: #4f4f4f;">FAQ</a>
            </li>
            <li class="mb-1">
              <a href="#!" class="text-decoration-none" style="color: #4f4f4f;">Classes</a>
            </li>
            <li class="mb-1">
              <a href="#!" class="text-decoration-none" style="color: #4f4f4f;">Pricing</a>
            </li>
            <li>
              <a href="#!" class="text-decoration-none" style="color: #4f4f4f;">Safety</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-1 text-dark">opening hours</h5>
          <table class="table" style="border-color: #666;">
            <tbody>
              <tr>
                <td>Mon - Fri:</td>
                <td>8am - 9pm</td>
              </tr>
              <tr>
                <td>Sat - Sun:</td>
                <td>8am - 1am</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="text-white text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white text-decoration-none " href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>

<!-- End of .container -->

templates/inc/loader.html
{% block style %}
    <style>

        .loader {
            position: fixed;
            top: 0;
            left: 0;
            width: 100vw;
            height: 100vh;
            display: flex;
            z-index: 1;
            align-items: center;
            justify-content: center;
            background: #000000;
            transition: opacity 1.75s, visibility 0.75s;
        }

        .loader--hidden {
            opacity: 0;
            visibility: hidden;
        }

        /* HTML: <div class="loader"></div> */

        /* HTML: <div class="loader"></div> */
        .loder {
            width: 50px;
            aspect-ratio: 1;
            display: grid;
            border: 4px solid #0000;
            border-radius: 50%;
            border-color: #ccc #0000;
            animation: l16 1s infinite linear;
        }

        .loder::before,
        .loder::after {
            content: "";
            grid-area: 1/1;
            margin: 2px;
            border: inherit;
            border-radius: 50%;
        }

        .loder::before {
            border-color: #f03355 #0000;
            animation: inherit;
            animation-duration: .5s;
            animation-direction: reverse;
        }

        .loder::after {
            margin: 8px;
        }

        @keyframes l16 {
            100% {
                transform: rotate(1turn)
            }
        }
    </style>
{% endblock %}
{% block content %}
    <div class="loader">
        <div class="loder"></div>
    </div>

{% endblock %}
{% block script %}
    <script>
        window.addEventListener('load', () => {
            const loader = document.querySelector(".loader")
            loader.classList.add('loader--hidden')
            loader.addEventListener('transitionend', () => {
                document.body.removeChild(document.querySelector('.loader'))
            })
        })
    </script>
{% endblock %}

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert {{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-dark back-header">
    <div class="container-fluid">
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link text-dark  fw-bold fs-5" href="{% url 'main:main' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link text-dark  fw-bold fs-5 dropdown-toggle" href="#"
                       id="navbarDarkDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Trainings
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                        {% for category in categories %}
                            {% if category.is_root_node %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark  fw-bold fs-5 dropdown-toggle" href="#"
                                       id="navbarDarkDropdownMenuLink" role="button"
                                       data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ category.name }}
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-dark"
                                        aria-labelledby="navbarDarkDropdownMenuLink">
                                        {% if category.get_children %}
                                            {% for child in category.get_children %}
                                                <li><a class=" dropdown-item" href="">{{ child.name }}</a></li>
                                            {% endfor %}
                                        {% endif %}
                                    </ul>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark  fw-bold fs-5" href="{% url 'main:main' %}">CART {{ cart|length }}</a>
                </li>

            </ul>
            {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:user_logout' %}" class="btn btn-header">Login Out</a>&nbsp;
                <a href="{% url 'accounts:user_profile' %}" class="btn btn-header ">Profile</a>

            {% else %}
                <a href="{% url 'accounts:user_login' %}" class="btn btn-header ">Login/Register</a>
            {% endif %}


        </div>
    </div>
</nav>